//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bai_tap_lon_web_trang_suc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public int ID_ChiTietDonHang { get; set; }
        public Nullable<int> ID_SanPham { get; set; }
        public Nullable<int> ID_DonHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public Nullable<double> GiamGia { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
