//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bai_tap_lon_web_trang_suc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhap
    {
        public int ID_ChiTietPhieuNhap { get; set; }
        public Nullable<int> ID_PhieuNhap { get; set; }
        public Nullable<int> ID_SanPham { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
