//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bai_tap_lon_web_trang_suc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class HinhAnh
    {
        public int ID_HinhAnh { get; set; }
        public Nullable<int> ID_SanPham { get; set; }
        public string hinhanh1 { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }
    }
}
